### ISSUE TITLE
Stop hotkey

### ISSUE THREAD

**Issue by Cherkah** [maandree/mongotimer#1]
hey, thank alot for your work :)

the only way to stop the app, we have to use the "CTRL + c" strike
Can you replace it with the "ESCAPE" or the "Q" key par exemple; and reporte it to the read me.

thank you

**Comment by maandree** [comment]
Absolutely, I will fix it next week, assuming I don't forget.

**Comment by maandree** [comment]
I've added the 'q' key command.
